title: "Learning Deep Low-Dimensional Models from High-Dimensional Data: From Theory to Practice"
description: >- # this means to ignore newlines until "baseurl:"
  'Website for ICCV 2025 Tutorial "Learning Deep Low-Dimensional Models from High-Dimensional Data: From Theory to Practice"'
baseurl: "/iccv2025-tutorial" # the subpath of your site, e.g. /blog
url: "https://low-dim-models-tutorials.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
# remote_theme: yous/whiteglass
theme: jekyll-whiteglass
plugins:
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Collections
collections:
  organizers:
  panelists:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: organizers
    values:
      layout: organizer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: panelists
    values:
      layout: organizer
      subpath: '/assets/images/'
  # - scope:
  #     path: ''
  #   values:
  #     image: /assets/sam-2023.jpeg

jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
